/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AGrid: typeof import('@arco-design/web-vue')['Grid']
    AGridItem: typeof import('@arco-design/web-vue')['GridItem']
    AGridItemc: typeof import('@arco-design/web-vue')['GridItemc']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    GlobalFooter: typeof import('./components/layout/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./components/layout/GlobalHeader.vue')['default']
    GlobalLayout: typeof import('./components/layout/GlobalLayout.vue')['default']
    IconDashboard: typeof import('@arco-design/web-vue/es/icon')['IconDashboard']
    IconExport: typeof import('@arco-design/web-vue/es/icon')['IconExport']
    IconFullscreen: typeof import('@arco-design/web-vue/es/icon')['IconFullscreen']
    IconFullscreenExit: typeof import('@arco-design/web-vue/es/icon')['IconFullscreenExit']
    IconMoonFill: typeof import('@arco-design/web-vue/es/icon')['IconMoonFill']
    IconRefresh: typeof import('@arco-design/web-vue/es/icon')['IconRefresh']
    IconSearch: typeof import('@arco-design/web-vue/es/icon')['IconSearch']
    IconSunFill: typeof import('@arco-design/web-vue/es/icon')['IconSunFill']
    IconUser: typeof import('@arco-design/web-vue/es/icon')['IconUser']
    Menu: typeof import('./components/menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableFilter: typeof import('./components/tableFilter/index.vue')['default']
  }
}
